version: '3.4'
services:
  zoo1:
    image: zookeeper:3.7.0
    container_name: c_zoo1
    hostname: hostzoo1
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=hostzoo1:2888:3888;2181 server.2=hostzoo2:2888:3888;2181
    volumes:
      - "/Users/wuguozhang/dockerkafka/zoo1/data:/data"
      - "/Users/wuguozhang/dockerkafka/zoo1/log:/data/log"
    networks:
      - shorturlkafka

  zoo2:
    image: zookeeper:3.7.0
    container_name: c_zoo2
    hostname: hostzoo2
    ports:
      - 22182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=hostzoo1:2888:3888;2181 server.2=hostzoo2:2888:3888;2181
    volumes:
      - "/Users/wuguozhang/dockerkafka/zoo2/data:/data"
      - "/Users/wuguozhang/dockerkafka/zoo2/log:/data/log"
    networks:
      - shorturlkafka

  kafka1:
    image: bitnami/kafka:3.1.0
    container_name: c_kafka1
    volumes:
      - /Users/wuguozhang/dockerkafka/kafka1:/bitnami/kafka
    depends_on:
      - zoo1
      - zoo2
    ports:
      - 29093:9093
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=hostzoo1:2181,hostzoo2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://192.168.3.62:29093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - shorturlkafka
    
  kafka2:
    image: bitnami/kafka:3.1.0
    container_name: c_kafka2
    volumes:
      - /Users/wuguozhang/dockerkafka/kafka2:/bitnami/kafka
    depends_on:
      - zoo1
      - zoo2
    ports:
      - 29094:9094
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=hostzoo1:2181,hostzoo2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://192.168.3.62:29094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - shorturlkafka

  kafka3:
    image: bitnami/kafka:3.1.0
    container_name: c_kafka3
    volumes:
      - /Users/wuguozhang/dockerkafka/kafka3:/bitnami/kafka
    depends_on:
      - zoo1
      - zoo2
    ports:
      - 29095:9095
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=hostzoo1:2181,hostzoo2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://192.168.3.62:29095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - shorturlkafka
      
networks:
  shorturlkafka:
    driver: bridge
