version: '3.4'
services:
  zoo1:
    image: zookeeper:3.7.0
    container_name: c_zoo1
    hostname: hostzoo1
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=hostzoo1:2888:3888;2181
    volumes:
      - "/data/zoodata/data:/data"
      - "/data/zoodata/log:/data/log"
    networks:
      - shorturlkafka

  kafka1:
    image: bitnami/kafka:3.1.0
    container_name: c_kafka1
    user: root
    volumes:
      - /data/kafkadata/kafka1:/bitnami/kafka
    depends_on:
      - zoo1
    ports:
      - 29093:9093
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=hostzoo1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://172.17.0.1:29093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - shorturlkafka
    
  kafka2:
    image: bitnami/kafka:3.1.0
    container_name: c_kafka2
    user: root
    volumes:
      - /data/kafkadata/kafka2:/bitnami/kafka
    depends_on:
      - zoo1
    ports:
      - 29094:9094
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=hostzoo1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://172.17.0.1:29094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - shorturlkafka

networks:
  shorturlkafka:
    driver: bridge
